CREATE DATABASE IF NOT EXISTS dbIngenieria
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE dbIngenieria;

CREATE TABLE IF NOT EXISTS SIRU_DSL (
    ID_INTERNO BIGINT NULL,
    DIVISIONAL VARCHAR(255) NULL,
    SITIO_UNINET VARCHAR(255) NULL,
    NOMBRE_EQUIPO VARCHAR(255) NULL,
    UBICACION VARCHAR(255) NULL,
    MODELO VARCHAR(255) NULL,
    FOLIO_DI_EQPO VARCHAR(255) NULL,
    STATUS_EQUIPO VARCHAR(100) NULL,
    LICENCIA VARCHAR(255) NULL,
    FUNCIONALIDAD VARCHAR(255) NULL,
    NUM_PARTE_TARJETA VARCHAR(255) NULL,
    STATUS_TARJETA VARCHAR(100) NULL,
    NUM_PARTE_SUBTARJETA VARCHAR(255) NULL,
    STATUS_SUBTARJETA VARCHAR(100) NULL,
    CHASIS VARCHAR(255) NULL,
    SLOT VARCHAR(100) NULL,
    SUBSLOT VARCHAR(100) NULL,
    PUERTO VARCHAR(100) NULL,
    TIPO_ASIG VARCHAR(255) NULL,
    PISO VARCHAR(100) NULL,
    SALA VARCHAR(100) NULL,
    FILA VARCHAR(100) NULL,
    ELEMENTO_DE_FILA VARCHAR(100) NULL,
    PATCH_PANEL VARCHAR(255) NULL,
    POS_REMATE VARCHAR(255) NULL,
    DESCRIPCION TEXT NULL,

    INDEX idx_siru_nombre_equipo (NOMBRE_EQUIPO),
    INDEX idx_siru_sitio (SITIO_UNINET),
    INDEX idx_siru_divisional (DIVISIONAL),
    INDEX idx_siru_slot (SLOT),
    INDEX idx_siru_status_equipo (STATUS_EQUIPO)
);

CREATE TABLE IF NOT EXISTS EQUIPOS_DSL_INTERFACE_L1 (
    ID_INTERFACE BIGINT NULL,
    ID_EQUIPO BIGINT NULL,
    SLOT VARCHAR(100) NULL,
    SHUTDOWN TINYINT NULL,
    DESCRIPCION TEXT NULL,
    ANCHO_BANDA VARCHAR(100) NULL,
    PROTOCOLO VARCHAR(100) NULL,
    TIPO VARCHAR(100) NULL,
    IP_ADDRESS VARCHAR(100) NULL,
    STATUS VARCHAR(100) NULL,
    VLAN VARCHAR(100) NULL,
    TRUNK VARCHAR(100) NULL,
    TRAFICO_95 DECIMAL(18, 4) NULL,
    OK_MET VARCHAR(10) NULL,

    INDEX idx_l1_interface (ID_INTERFACE),
    INDEX idx_l1_equipo (ID_EQUIPO),
    INDEX idx_l1_slot (SLOT),
    INDEX idx_l1_status (STATUS),
    INDEX idx_l1_shutdown (SHUTDOWN),
    INDEX idx_l1_ip (IP_ADDRESS),
    INDEX idx_l1_vlan (VLAN)
);

CREATE TABLE IF NOT EXISTS HISTORICO_DSL_INTERFACE (
    ID_HISTORICO BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_INTERFACE BIGINT NULL,
    ID_EQUIPO BIGINT NULL,
    SLOT VARCHAR(100) NULL,
    ANCHO_BANDA VARCHAR(100) NULL,
    TRAFICO_95 DECIMAL(18, 4) NULL,
    FECHA_SNAP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_hist_interface (ID_INTERFACE),
    INDEX idx_hist_equipo (ID_EQUIPO),
    INDEX idx_hist_slot (SLOT),
    INDEX idx_hist_fecha (FECHA_SNAP)
);

CREATE TABLE IF NOT EXISTS INFINITUM_dslSessionSemanal (
    ID INT NULL,
    HOSTNAME VARCHAR(100) NULL,
    TIPO VARCHAR(100) NULL,
    SLOT VARCHAR(100) NULL,
    MAX_USER_SESSION VARCHAR(100) NULL
);
